import type {Resolved} from '@nlib/typing';
import type {getPageList} from './getPageList';

export const pageListToTsModule = (
    {pageListByPublishedAt, toListByUpdatedAt}: Resolved<ReturnType<typeof getPageList>>,
) => `
// This file was generated by @gjbkz/gojabako.zone-build-pagelist
/* eslint-disable */
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    archiveOf?: string,
    description?: string,
}
export const pageListByPublishedAt: Array<PageData> = JSON.parse(
    ${JSON.stringify(JSON.stringify(pageListByPublishedAt))}
);
export const pageListByUpdatedAt: Array<PageData> = ${JSON.stringify(toListByUpdatedAt)}
.map((index) => pageListByPublishedAt[index]);
`.trim();
