import type {Resolved} from '@nlib/typing';
import type {getPageList} from './getPageList';

export const pageListToTsModule = (
    {pageListByPublishedAt, toListByUpdatedAt}: Resolved<ReturnType<typeof getPageList>>,
) => `
// This file was generated by @gjbkz/gojabako.zone-build-pagelist
/* eslint-disable */
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    archiveOf?: string,
    description?: string,
}
export const pageListByPublishedAt: Array<PageData> = ${JSON.stringify(pageListByPublishedAt, null, 4)};
export const pageListByUpdatedAt: Array<PageData> = ${JSON.stringify(toListByUpdatedAt, null, 4)}
.map((index) => pageListByPublishedAt[index]);
`.trimStart();

export const pageListToJsModule = (
    {pageListByPublishedAt, toListByUpdatedAt}: Resolved<ReturnType<typeof getPageList>>,
) => `
// @ts-check
/* eslint-disable */
// This file was generated by @gjbkz/gojabako.zone-build-pagelist
/** @typedef {{pathname: string, title: string, filePath: string, publishedAt: string, updatedAt: string, commitCount: number, archiveOf?: string, description?: string}} PageData */

/** @type {Array<PageData>} */
export const pageListByPublishedAt = ${JSON.stringify(pageListByPublishedAt, null, 4)};
/** @type {Array<PageData>} */
export const pageListByUpdatedAt = ${JSON.stringify(toListByUpdatedAt, null, 4)}.map((index) => pageListByPublishedAt[index]);
`.trimStart();
